name: project
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  carousel_slider: ^5.0.0
  flutter_test:
    sdk: flutter


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

flutter:
  assets:
    - assets/logo.png
  uses-material-design: true